### PR TITLE
Submint PRML Assignment-2

### PR DESCRIPTION
**Pull request by hungryzzz**
Submint PRML Assignment-2

### CODE REVIEW

**Comment by ichn-hu** [comment]
Sorry but your PR will not be merged as you changed files outside your own working directory.

**Comment by ichn-hu** [comment]
Please fix and resubmit it no later than tomorrow 6:30 PM.

**Comment by ichn-hu** [comment]
Do not delete others' submission.

**Comment by ichn-hu** [comment]
Reply me if you read this.

**Comment by hungryzzz** [comment]
> Reply me if you read this.

**Comment by hungryzzz** [comment]
> Reply me if you read this.

**Comment by hungryzzz** [comment]
> Reply me if you read this.

OK. I have merged other's submission.

**Pull request merged**
