### PR TITLE
submit assignment 2

### PR DESCRIPTION
**Pull request by HannanKan**

### CODE REVIEW

**Comment by ichn-hu** [comment]
Sorry but you should not modify the file in the handout directory, therefore your pr will not be merged.

A simpler solution is to copy the modified __init__.py file into your own directory, and re-commit and resubmit your code. Please do it quickly in order to get your coursework marked.

**Comment by HannanKan** [comment]
re- submit assignment-2

**Comment by ichn-hu** [comment]
Note that the commit history includes commit that changes the files outside your directory. I think you need to re fork, re clone and re commit in order to clean the commit history.

**Comment by ichn-hu** [comment]
I'll close this pr and wait for your new PR.

**Pull request closed without merging**
